from pydantic import BaseModel, Field

class TwilioFormData(BaseModel):
    called: str = Field(alias='Called')
    to_state: str = Field(alias='ToState')
    caller_country: str = Field(alias='CallerCountry')
    direction: str = Field(alias='Direction')
    caller_state: str = Field(alias='CallerState')
    to_zip: str = Field(alias='ToZip')
    call_sid: str = Field(alias='CallSid')
    call_to: str = Field(alias='To')
    caller_zip: str = Field(alias='CallerZip')
    to_country: str = Field(alias='ToCountry')
    called_zip: str = Field(alias='CalledZip')
    api_version: str = Field(alias='ApiVersion')
    called_city: str = Field(alias='CalledCity')
    call_status: str = Field(alias='CallStatus')
    call_from: str = Field(alias='From')
    account_sid: str = Field(alias='AccountSid')
    called_country: str = Field(alias='CalledCountry')
    caller_city: str = Field(alias='CallerCity')
    application_sid: str = Field(alias='ApplicationSid')
    to_city: str = Field(alias='ToCity')
    from_country: str = Field(alias='FromCountry')
    caller: str = Field(alias='Caller')
    from_city: str = Field(alias='FromCity')
    called_state: str = Field(alias='CalledState')
    from_zip: str = Field(alias='FromZip')
    from_state: str = Field(alias='FromState')
    stir_ver_stat: str = Field(alias='StirVerstat', default="")
    digits: str = Field(alias='Digits', default="")
    retry_count: str = Field(alias='RetryCount', default="")